default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
      files: (^src/|^setup.py|^tests/)
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]
      files: (^src/|^setup.py|^tests/)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort
      files: (^src/|^setup.py|^tests/)
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle
      additional_dependencies: [toml]
      files: ^src/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
    - id: mypy
      additional_dependencies: [types-requests]
      files: (^src/|^setup.py|^tests/)
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.2.0
    hooks:
    - id: pip-compile
      name: pip-compile setup.py
      args:
      - setup.py
      files: ^(setup\.py|requirements\.txt)$
    - id: pip-compile
      name: pip-compile requirements-dev.in
      args:
      - setup.py
      files: ^requirements-dev\.(in|txt)$