version: '3'
services: 
    sudoku-solver-ocr:
        build: ./code
        container_name: sudoku-solver-ocr
        volumes:
            - ./code:/code
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        environment: 
            - .env